server:
  port: 5555
spring:
  application:
    name: p2pBackend
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: p2p-storage-cluster
      auto-offset-reset: earliest
      properties:
        max.partition.fetch.bytes: 20971520 # 20MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/P2PFileShare

p2p:
  server:
    bootstrap: localhost:5555
    path: /Users/bogdan.marcu/shards
